{
 "title": "MainApp",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "MainApp Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"main_app-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DB Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"db-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Search Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "up{job=\"meilisearch-metrics\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Caddy Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "up{job=\"caddy\", instance!=\"localhost:2019\"}\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Redis Uptime",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 16 },
   "targets": [
    { "expr": "redis_up", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}